def format_articles_to_mobile_html(articles_list):
    """
    生成适配手机端的 HTML 邮件 (带 JCR 颜色分级)
    """
    html_start = """
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        /* 手机端基础样式 */
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 10px; background-color: #f4f4f4; }
        .card { background: white; border-radius: 8px; padding: 15px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        /* Tag 基础样式 */
        .tag { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; margin-bottom: 5px; margin-right: 5px;}
        .type-tag { background: #e3f2fd; color: #1565c0; } /* 默认蓝色给文献类型 */
        
        .meta { font-size: 13px; color: #666; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        .title-en { font-size: 16px; font-weight: bold; color: #2c3e50; margin-bottom: 8px; }
        .abstract-en { font-size: 14px; color: #555; margin-bottom: 15px; }
        .title-cn { font-size: 16px; font-weight: bold; color: #d35400; margin-bottom: 8px; }
        .abstract-cn { font-size: 14px; color: #333; background-color: #fff8e1; padding: 10px; border-radius: 4px; }
        .footer { text-align: center; font-size: 12px; color: #999; margin-top: 20px; }
    </style>
    </head>
    <body>
        <h3 style="text-align:center; color:#444;">今日文献推送</h3>
    """
    
    html_body = ""
    
    for idx, art in enumerate(articles_list, 1):
        if not isinstance(art, dict): continue

        # --- 1. 获取 JCR 和 IF ---
        jcr_val = str(art.get('JCR', 'N/A')).upper() # 转大写，防止 q1 和 Q1 不匹配
        if_val = art.get('IF', 'N/A')
        
        # --- 2. 核心逻辑：根据 JCR 决定颜色 ---
        # 默认灰色 (如果没有 JCR 数据)
        tag_style = "background:#f5f5f5; color:#616161;" 

        if 'Q1' in jcr_val:
            # Q1: 红色 (浅红底+深红字)
            tag_style = "background:#ffebee; color:#c62828;"
        elif 'Q2' in jcr_val:
            # Q2: 橙色 (浅橙底+深橙字)
            tag_style = "background:#fff3e0; color:#ef6c00;"
        elif 'Q3' in jcr_val:
            # Q3: 黄色 (浅黄底+深金字，纯黄看不清)
            tag_style = "background:#fffde7; color:#f9a825;"
        elif 'Q4' in jcr_val:
            # Q4: 绿色 (浅绿底+深绿字)
            tag_style = "background:#e8f5e9; color:#2e7d32;"

        # --- 3. 构造卡片 ---
        card = f"""
        <div class="card">
            <div>
                <span class="tag type-tag">#{idx} {art.get('TYPE', 'Article')}</span>
                
                <span class="tag" style="{tag_style}">IF: {if_val}</span>
                
                <span class="tag" style="{tag_style}">{jcr_val}</span>
            </div>

            <div class="meta">
                {art.get('JOURNAL', 'Journal')} | PMID: {art.get('PMID')}
            </div>

            <div class="title-en">{art.get('TITLE', 'No Title')}</div>
            <div class="abstract-en">{art.get('ABSTRACT', 'No Abstract')}</div>

            <hr style="border:0; border-top:1px dashed #ddd; margin: 15px 0;">

            <div class="title-cn">{art.get('TITLE_CN', '暂无翻译')}</div>
            <div class="abstract-cn">{art.get('ABSTRACT_CN', '暂无翻译')}</div>
        </div>
        """
        html_body += card

    html_end = """
        <div class="footer">Generated by Python Scripts</div>
    </body>
    </html>
    """
    
    return html_start + html_body + html_end

result4 = format_articles_to_mobile_html(result2)

with open("email_preview.html", "w", encoding="utf-8") as f:
    f.write(result4)
